slam_toolbox:
  ros__parameters:
    use_sim_time: True
    map_frame: map
    base_frame: base_footprint
    odom_frame: odom
    scan_topic: /scan

    # Processamento/tempo
    transform_publish_period: 0.05
    transform_timeout: 0.2
    minimum_time_interval: 0.0

    # Fila e amostragem
    scan_queue_size: 50
    throttle_scans: 1   # 1 = processar todos (a 5 Hz não é problema)

    # Sensor (coerente com o teu LiDAR)
    resolution: 0.05
    max_laser_range: 3.5
